# Site settings
title: OpenBeta
description: OpenBeta Description
relative_permalinks: false
markdown: kramdown
baseurl: "/dev" # the subpath of your site, e.g. /blog

# Concepts Pages
collections:
  concepts:
    output: true
    permalink: /concepts/:path/
defaults: 
  -
    scope:
      path: ""
      type: "concepts"
    values:
      layout: concept
