# Site settings
title: OpenBeta
description: OpenBeta Description
relative_permalinks: false
markdown: kramdown
baseurl: "/dev" # the subpath of your site, e.g. /blog
disqus_shortname: "dataact-openbeta" # this is the shortname found in the Disqus admin settings

# Concepts Pages
collections:
  concepts:
    output: true
    permalink: /concepts/:path/
defaults: 
  -
    scope:
      path: ""
      type: "concepts"
    values:
      layout: concept
