# Site settings
title: OpenBeta
description: OpenBeta Description
relative_permalinks: false
markdown: kramdown
baseurl: "/dev" # the subpath of your site, e.g. /blog

# Concepts Pages
collections:
  concepts:
    output: true
    permalink: /concepts/:path/
defaults:
  -
    scope:
      path: ""
      type: "concepts"
    values:
      layout: concept

# Plugin configuration
jekyll_timeago:
  depth: 1

# Disqus
disqus_shortname: "dataact-openbeta" # this is the shortname found in the Disqus admin settings
disqus_api_key: "Kqjb4gW6YBIkqtMI2u8OMkVoUBAAPlZVWsO5ZoJS68PpMGIkVQaCsdhT3I1zfuph" # a public key used to make API requests

# Google Analytics
google_analytics_id: "UA-77512441-1"

# Socrata
socrata_app_token: IpvjLVLiUoqVIUomSdwugAOwe
socrata_data_site: openbeta-data.usaspending.gov