# Site settings
title: OpenBeta
description: OpenBeta Description
relative_permalinks: false
markdown: kramdown
url: "http://yourdomain.com"

# Concepts Pages
collections:
  concepts:
    output: true
    permalink: /concepts/:path/
defaults: 
  -
    scope:
      path: ""
      type: "concepts"
    values:
      layout: concept