# Site settings
title: OpenBeta
description: OpenBeta Description
relative_permalinks: false
markdown: kramdown
url: "http://treasury-dact-jekyll.s3-website-us-east-1.amazonaws.com/dev/"

# Concepts Pages
collections:
  concepts:
    output: true
    permalink: /concepts/:path/
defaults: 
  -
    scope:
      path: ""
      type: "concepts"
    values:
      layout: concept