# Site settings
title: OpenBeta
description: "OpenBeta.USAspending.gov is where the public can comment on all of the design concepts that will be the basis for the new USAspending.gov."
relative_permalinks: false
markdown: kramdown
baseurl: "/dev" # the subpath of your site, e.g. /blog

# Concepts Pages
collections:
  concepts:
    output: true
    permalink: /concepts/:path/
defaults:
  -
    scope:
      path: ""
      type: "concepts"
    values:
      layout: concept

# Plugin configurations
jekyll_timeago:
  depth: 1

# Disqus
disqus_shortname: "dataact-openbeta" # this is the shortname found in the Disqus admin settings
disqus_api_key: "Kqjb4gW6YBIkqtMI2u8OMkVoUBAAPlZVWsO5ZoJS68PpMGIkVQaCsdhT3I1zfuph" # a public key used to make API requests

# Google Analytics
google_analytics_id: "UA-66828913-1"

# Socrata
socrata_app_token: IpvjLVLiUoqVIUomSdwugAOwe
socrata_data_site: data.fedspending.gov

# excludes
exclude: [vendor]
